networks:
  prati.net:
    driver: bridge

services:
  api.prati:
    build:
      context: build
      dockerfile: 8.4-cli.Dockerfile
    ports:
      - '6080:80'
    volumes:
      - ./app:/var/php
    working_dir: /var/php
    networks:
      - prati.net
    depends_on:
      - prati.db
    command: sh -c "composer install && php -S 0.0.0.0:80 -t /var/php/public"

  prati.db:
    image: 'postgres:latest'
    env_file: ./env/prati.env
    ports:
      - '5432:5432'
    networks:
      - prati.net
    volumes:
      # - ./sql:/var/sql
      - ./sql/prati:/docker-entrypoint-initdb.d/

  adminer:
    image: adminer
    ports:
      - '8080:8080'
    networks:
      - prati.net

